version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  py36:
    docker:
    - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install tox && tox -e py36
  py37:
    docker:
    - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip install tox && tox -e py37
  py38:
    docker:
    - image: circleci/python:3.8
    steps:
      - checkout
      - run: pip install tox && tox -e py38

workflows:
  main:
    jobs:
      - toxify
