version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  tox:
    docker:
    - image: circleci/python:<<parameters.python_version>>
    steps:
      - checkout
      - run: pip install tox && tox -e <<parameters.tox_env>>

workflows:
  main:
    jobs:
      - tox:
          parameters:
          - tox_env: py36
            python_version: 3.6
          - tox_env: py37
            python_version: 3.7
          - tox_env: py38
            python_version: 3.8
