version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  # using tox
  toxify:
      docker:
      - image: circleci/python:latest
      steps:
        - checkout
        - run: pip install tox && tox

workflows:
  main:
    jobs:
      - toxify
